name: dashboard-backend
services:
    postgres:
        container_name: postgres
        environment:
            - POSTGRES_PASSWORD=1234
        volumes:
            - postgres:/var/lib/postgresql/data
        image: postgres:17.6-alpine3.22
        ports:
            - 5432:5432
    #dashboard_backend:
    #    volumes:
     #       - .:/app
     #   container_name: dashboard_backend
      #  build: .
       # environment:
        #    - DATABASE_URL=${DATABASE_URL}
        #depends_on:
        #    - postgres
        #ports:
         #   - 3000:3000
    json-server:
        ports:
            - 80:80
        volumes:
            - ./json-server/db.json:/data/db.json
        image: clue/json-server
volumes:
    postgres: